---
name: "StockPrediction"
dataIns:
workflowBody:
  - function:
      name: "Function1"
      dataIns:
      dataOuts:
        - name: "statusCode"
          type: "string"
        - name: "body"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "ASYNC"
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:717556240325:function:asdfasdf"
  - function:
      name: "Function2"
      dataIns:
      dataOuts:
        - name: "statusCode"
          type: "string"
        - name: "body"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "SYNC"
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:717556240325:function:asdfasdf"
dataOuts:
  - name: "resultA"
    type: "collection"
    source: "Function1/outputA"
  - name: "resultB"
    type: "collection"
    source: "Function2/outputA"