---
name: "Example"
dataIns:
workflowBody:
  - function:
      name: "Function1"
      type: "function"
      dataIns:
      dataOuts:
        - name: "statusCode"
          type: "string"
        - name: "body"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "SYNC"
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:717556240325:function:asdfasdf"
  - function:
      name: "asyncShit"
      type: "build-in:asyncHandler"
      dataIns:
        - name: "functions"
          type: "collection"
          value: "Function1"
      dataOuts:
        - name: "statusCode"
          type: "string"
        - name: "body"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "SYNC"
dataOuts:
  - name: "resultA"
    type: "collection"
    source: "Function1/outputA"
  - name: "resultB"
    type: "collection"
    source: "Function2/outputA"