---
name: "Example"
dataIns:
- name: "parameters"
  type: "collection"
  source: "parameters"
workflowBody:
  - function:
      name: "Helper"
      type: "function"
      dataIns:
        - name: "parameters"
          type: "collection"
          source: "Example/parameters"
      dataOuts:
        - name: "sum"
          type: "number"
        - name: "list"
          type: "collection"
      properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-1:180575510797:function:helperFunction"
  - function:
      name: "FirstStep"
      type: "function"
      dataIns:
        - name: "list"
          type: "collection"
          source: "Helper/list"
        - name: "sum"
          type: "number"
          source: "Helper/sum"
      dataOuts:
        - name: "newData"
          type: "number"
        - name: "oldData"
          type: "number"
      properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-1:180575510797:function:preCalculation"
  - function:
      name: "SaveData"
      type: "function"
      dataIns:
        - name: "newData"
          type: "number"
          source: "FirstStep/newData"
        - name: "oldData"
          type: "number"
          source: "FirstStep/oldData"
      dataOuts:
        - name: "statusCode"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "SYNC"
        - name: "resource"
          value: "arn:aws:lambda:us-east-1:180575510797:function:saveData"
  - function:
      name: "UserOutput"
      type: "function"
      dataIns:
        - name: "newData"
          type: "number"
          source: "SaveData/newData"
        - name: "oldData"
          type: "number"
          source: "SaveData/oldData"
      dataOuts:
        - name: "output"
          type: "string"
      properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-1:180575510797:function:UserOutput"
dataOuts:
- name: "output"
  type: "string"
  source: "UserOutput/output"
