---
name: "StockPrediction"
dataIns:
workflowBody:
  - function:
      name: "Function1"
      dataIns:
      dataOuts:
        - name: "statusCode"
          type: "string"
        - name: "body"
          type: "string"
      properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:717556240325:function:asdfasdf"
dataOuts:
  - name: "result"
    type: "collection"
    source: "Function1/outputA"