---
name: "Example"
dataIns:
workflowBody:
  - function:
      name: "Function1"
      type: "function"
      dataIns:
      dataOuts:
        - name: "statusCode"
          type: "string"
        - name: "response"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "ASYNC"
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:717556240325:function:asdfasdf"
      constraints:
        - name: "FT-AltPlan-0"
          value: "1;arn:aws:lambda:us-east-2:717556240325:function:testasdfasdf;"
  - function:
      name: "asyncShit"
      type: "build-in:asyncHandler"
      dataIns:
        - name: "functions"
          type: "collection"
          value: "Function1"
      dataOuts:
        - name: "handlerOutput"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "SYNC"
  - function:
      name: "Function1"
      type: "function"
      dataIns:
      dataOuts:
        - name: "statusCode"
          type: "string"
        - name: "response"
          type: "string"
      properties:
        - name: "invoke-type"
          value: "ASYNC"
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:717556240325:function:asdfasdf"
dataOuts:
